### ISSUE TITLE
Cannot build project with new `print-one` version

### ISSUE THREAD

**Issue by alianza** [Print-one/print-one-js#23]
**Describe the bug**
I cannot build my project using typescript with `print-one` higher than v1.0.0. When upgrading `print-one` to v1.2.1 and build the project I get.

```
node_modules/@print-one/print-one-js/lib/models/CsvOrder.d.ts:7:50 - error TS2307: Cannot find module 'src/enums/CsvStatus' or its corresponding type declarations.

7 import { CsvStatus, FriendlyCsvStatusText } from "src/enums/CsvStatus";
                                                   ~~~~~~~~~~~~~~~~~~~~~
Found 1 error in node_modules/@print-one/print-one-js/lib/models/CsvOrder.d.ts:7
```

This is easily fixed with a manual patch of `import { CsvStatus, FriendlyCsvStatusText } from "src/enums/CsvStatus";` to `import { CsvStatus, FriendlyCsvStatusText } from "../enums/CsvStatus";`

This only happens when using a typescript target above ES2015. We'd like to be able to use more modern ES versions like 2023 but encounter this issue when doing so.

**To Reproduce**

1. Install `print-one` npm package
2. Install `typescript`
3. Raise `tsconfig` target to > ES2015
4. Build using `tsc`
5. Oberseve errors in `print-one` node module

**Expected behavior**
Build succeeds with no issues

**Comment by UnderKoen** [comment]
Thanks for reporting, we had fixxed this with https://github.com/Print-one/print-one-js/pull/19 but unfortunately forgot to check if the deploy was succesfull. This is now fixxed in https://github.com/Print-one/print-one-js/releases/tag/v1.3.0

**Comment by alianza** [comment]
Amazing, thanks for the quick reply!
